## Perform CRISPR-related analyses for ENCODE-rE2G manuscript

configfile: "config/config.yml"

# ENCODE-rE2G prediction and enhancer list files
configfile: "config/encode_re2g_predictions.yml"
configfile: "config/encode_re2g_enhancer_lists.yml"

# include rules for all analyses
include: "rules/crispr_benchmarking.smk"
include: "rules/other_analyses.smk"
include: "rules/enhancer_definitions.smk"  # helper functions for analysis in Extended Data Fig. 7

# rule to produce all workflow output for the manuscript
rule all:
  input:
    "results/manuscript/fig1b_prkar2b_locus.html",
    "results/manuscript/fig2bc_main_crispr_benchmarks.html",
    "results/manuscript/heldout_crispr_benchmarks.html",
    "results/manuscript/fig3e_gwas_locus.html",
    "results/manuscript/plots/fig4a_prkar2b_features.pdf",
    "results/manuscript/assaying_enhancer_activity.html",
    "results/manuscript/fig4fg_additional_models.html",
    "results/manuscript/extended_data_fig1_feature_correlation.html",
    "results/manuscript/extended_data_fig2_crispr_benchmarking.html",
    "results/manuscript/extended_data_fig3a_perf_eg_classes.html",
    "results/manuscript/extended_data_fig3bcd_additional_models.html",
    "results/manuscript/plots/extended_data_fig6abc_property_plots.pdf",
    "results/manuscript/plots/extended_data_fig7_enhancer_definitions.pdf",
    "results/manuscript/supplementary_note_N1_crispr_datasets.html",
    "results/manuscript/indirect_effects_analyses.html",
    expand("results/manuscript/plots/supplementary_figN5.2_gwas_locus_plots/{snp}_locus_plot.pdf",
       snp = ["rs4927708", "rs218265", "rs7599488"]),
    expand("results/manuscript/plots/supplementary_fig1_crispr_locus_plots/{gene}_locus_plot.pdf",
       gene = ["hbe1", "myc", "gata1"]),
    "results/manuscript/plots/supplementary_fig1_crispr_locus_plots/myc_locus_plot_zoomed.pdf",
    "results/manuscript/supplementary_fig2_crispr_benchmarks.html",
    "results/manuscript/supplementary_fig3_predictors_vs_crispr_effects.html",
    "results/manuscript/plots/supplementary_fig4_encode_re2g_vs_gene_expression.pdf",
    "results/manuscript/plots/supplementary_fig5a_activity_vs_distance.pdf",
    "results/manuscript/tables/supplementary_table2_encode_re2g_metadata_combined.csv",
    "results/manuscript/tables/supplementary_table3_crispr_performance_summary.csv",
    "results/manuscript/tables/supplementary_table8_encode_re2g_stats_per_biosample.csv",
    "results/manuscript/tables/supplementary_table9_encode_re2g_stats_per_gene.csv",    
    "results/manuscript/tables/supplementary_table16_baseline_predictors.csv",
    "results/manuscript/tables/supplementary_table17_enhancer_activity_files.csv"


# Helper rules to download various required inputs -------------------------------------------------

# download GENCODE v29 genome annotations used in analyses
rule download_genome_annotation:
  output: "resources/gencode.v29.annotation.gtf.gz"
  params:
    url = "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz"
  conda: "envs/analyses_env.yml"
  shell:
    "wget -O {output} {params.url}"

# download .bed file (peak) from the ENCODE portal
rule download_encode_file:
  output: "resources/{accession}.bed.gz"
  params:
    url = "https://www.encodeproject.org/files/{accession}/@@download/{accession}.bed.gz"
  conda: "envs/analyses_env.yml"
  shell:
    "wget -O {output} {params.url}"
    
# download .bigWig (assay signal) from the ENCODE portal    
rule download_encode_bigwig:
  output: "resources/{accession}.bigWig"
  params:
    url = "https://www.encodeproject.org/files/{accession}/@@download/{accession}.bigWig"
  conda: "envs/analyses_env.yml"
  shell:
    "wget -O {output} {params.url}"  

# download .bam (aligned reads) from the ENCODE portal    
rule download_encode_bam:
  output:
    bam = temp(config["scratch_dir"] + "/{accession}.bam"),
    sorted_bam = config["scratch_dir"] + "/{accession}.sorted.bam",
    sorted_bai = config["scratch_dir"] + "/{accession}.sorted.bam.bai"
  params:
    url = "https://www.encodeproject.org/files/{accession}/@@download/{accession}.bam"
  conda: "envs/analyses_env.yml"
  resources:
    mem = "32G"
  shell:
    "wget -O {output.bam} {params.url}; "
    "samtools sort -o {output.sorted_bam} {output.bam}; "
    "samtools index {output.sorted_bam}"
