---
title: "CRISPR data supplementary note"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Andreas R. Gschwind"
output: html_document
---

```{r setupDocument, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r attachPackages, message=FALSE, warning=FALSE}
# attach required packages and functions
library(tidyverse)
library(data.table)
library(ggExtra)
library(cowplot)
```

## Goal
Create plots for CRISPR data supplementary note.

***

## Panel B,C: Power analysis results

```{r}
# load CRISPR data
gasp_crispr <- read_tsv(snakemake@input$gasp_crispr, show_col_types = FALSE)
schrai_crispr <- read_tsv(snakemake@input$schrai_crispr, show_col_types = FALSE)
```

```{r, fig.height=4, fig.width=7.5}
# extract power and reformat
gasp_power <- gasp_crispr %>% 
  select(name, Regulated, starts_with("PowerAtEffectSize")) %>%
  pivot_longer(cols = starts_with("PowerAtEffectSize"), names_to = "effect_size",
               values_to = "power") %>% 
  mutate(effect_size = sub("PowerAtEffectSize(.+)", "\\1%", effect_size))

# set power to 0 for any pairs with power = NA
gasp_power <- replace_na(gasp_power, replace = list(power = 0))

# add power rank and percent of pairs
gasp_power <- gasp_power %>% 
  group_by(effect_size) %>% 
  arrange(desc(power)) %>% 
  mutate(power_rank = seq_len(n()),
         power_pct = power_rank / n())

# plot power distribution
p1 <- ggplot(gasp_power, aes(x = power_pct, y = power, color = effect_size)) +
  geom_hline(yintercept = 0.8, lty = "dashed") +
  geom_line(lwd = 1) +
  labs(title = "Power across tested pairs", y = "Power", x = "Tested perturbation-gene pairs",
       color = "Effect size") +
  scale_x_continuous(labels = scales::percent) +
  theme_bw() +
  theme(text = element_text(size = 12), panel.grid = element_blank())

# plot number of pairs at 80% power
p2 <- ggplot(filter(gasp_power, power >= 0.8), aes(x = effect_size, fill = effect_size)) +
  geom_bar() +
  scale_y_continuous(limits = c(0, nrow(gasp_crispr))) +
  labs(x = "Effect size", y = "Tested perturbation-gene pairs", title = "80% power") +
  theme_bw() +
  theme(legend.position = "none", text = element_text(size = 12), panel.grid = element_blank(),
        axis.text.x = element_text(size = 9))

# print plots as one figure
power_gasp_plot <- plot_grid(p2, p1, ncol = 2, rel_widths = c(0.33, 0.66))
```

```{r, fig.height=4, fig.width=7.5}
# extract power and reformat
schrai_power <- schrai_crispr %>% 
  select(name, Regulated, starts_with("PowerAtEffectSize")) %>%
  pivot_longer(cols = starts_with("PowerAtEffectSize"), names_to = "effect_size",
               values_to = "power") %>% 
  mutate(effect_size = sub("PowerAtEffectSize(.+)", "\\1%", effect_size))

# set power to 0 for any pairs with power = NA
schrai_power <- replace_na(schrai_power, replace = list(power = 0))

# add power rank and percent of pairs
schrai_power <- schrai_power %>% 
  group_by(effect_size) %>% 
  arrange(desc(power)) %>% 
  mutate(power_rank = seq_len(n()),
         power_pct = power_rank / n())

# plot power distribution
p1 <- ggplot(schrai_power, aes(x = power_pct, y = power, color = effect_size)) +
  geom_hline(yintercept = 0.8, lty = "dashed") +
  geom_line(lwd = 1) +
  labs(title = "Power across tested pairs", y = "Power", x = "Tested perturbation-gene pairs",
       color = "Effect size") +
  scale_x_continuous(labels = scales::percent) +
  theme_bw() +
  theme(text = element_text(size = 12), panel.grid = element_blank())

# plot number of pairs at 80% power
p2 <- ggplot(filter(schrai_power, power >= 0.8), aes(x = effect_size, fill = effect_size)) +
  geom_bar() +
  scale_y_continuous(limits = c(0, nrow(schrai_crispr))) +
  labs(x = "Effect size", y = "Tested perturbation-gene pairs", title = "80% power") +
  theme_bw() +
  theme(legend.position = "none", text = element_text(size = 12), panel.grid = element_blank(),
        axis.text.x = element_text(size = 9))

# print plots as one figure
power_schrai_plot <- plot_grid(p2, p1, ncol = 2, rel_widths = c(0.33, 0.66))
```

***

## Panel D: Number of genes and elements screened in combined CRISPR data

```{r}
# load combined K562 CRISPR training dataset
combinedData <- read_tsv(snakemake@input$combined_crispr, show_col_types = FALSE)

# make sure that the data only contains valid connections
combinedData <- filter(combinedData, ValidConnection == "TRUE")
```

```{r}
# add pretty dataset labels
combinedData <- combinedData %>% 
  mutate(dataset_label = case_when(
    Dataset == "Nasser2021" ~ "Nasser et al., 2021",
    Dataset == "Gasperini2019" ~ "Gasperini et al., 2019",
    Dataset == "Schraivogel2020" ~ "Schraivogel et al., 2020"
  )) %>% 
  mutate(dataset_label = fct_relevel(dataset_label, "Schraivogel et al., 2020"))

# count the number of unique genes and enhancers in CRISPR data
n_elements <- combinedData %>% 
  mutate(enh_id = paste0(chrom, ":", chromStart, "-", chromEnd)) %>% 
  group_by(dataset_label) %>% 
  summarize(Elements = n_distinct(enh_id),
            Genes = n_distinct(measuredGeneSymbol)) %>% 
  pivot_longer(cols = c(Elements, Genes), names_to = "element", values_to = "count")

# plot the number of elements and genes per dataset
p1 <- ggplot(n_elements, aes(y = dataset_label, x = count, fill = element)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(group = element, label = count), position = position_dodge(width = 0.9),
            hjust = -0.05, size = 3.1) + 
  labs(title = "CRISPR elements and genes", x = "Elements / genes", fill = "Type") +
  scale_fill_manual(values = c("Elements" = "goldenrod2", "Genes" = "dodgerblue3")) +
  scale_x_continuous(limits = c(0, 2500)) +
  theme_classic() +
  theme(legend.position = "bottom", axis.title.y = element_blank())

# count the number of positive and negative pairs
n_pairs <- combinedData %>% 
  filter(!is.na(Regulated)) %>% 
  count(dataset_label, Regulated, name = "pairs") %>% 
  mutate(Regulated = if_else(Regulated == TRUE, true = "Pos.", false = "Neg."))

# create table with positive and negative numbers of pairs per dataset for labels
n_pairs_labels <- n_pairs %>% 
  pivot_wider(names_from = Regulated, values_from = pairs) %>% 
  mutate(pairs_label = paste0(Pos., " pos.\n", Neg., " neg."),
         total_pairs = Pos. + Neg.)

# plot the number of E-G pairs per dataset
p2 <- ggplot(n_pairs, aes(x = pairs, y = dataset_label)) +
  geom_bar(aes(fill = Regulated), stat = "identity") +
  geom_text(data = n_pairs_labels, aes(x = total_pairs, y = dataset_label, label = pairs_label),
            hjust = -0.05, size = 3.1) + 
  labs(title = "CRISPR E-G pairs", x = "E-G pairs", fill = "Result") +
  scale_fill_manual(values = c("Pos." = "firebrick2", "Neg." = "gray55")) +
  scale_x_continuous(limits = c(0, 7000)) +
  theme_classic() +
  theme(legend.position = "bottom",  axis.title.y = element_blank(), axis.text.y = element_blank())

# arrange plots
n_crispr_pairs <- plot_grid(p1, p2, ncol = 2, rel_widths = c(1, 0.65))
```

***

## Panel E: CRISPR E-G pair properties

```{r}
# select enhancer activity measurements to plot and convert to long format
enh_activity <- combinedData %>% 
  unite(col = element, chrom, chromStart, chromEnd) %>% 
  select(element, dataset_label, `DNase-seq` = DHS.RPM, H3K27ac = H3K27ac.RPM) %>% 
  distinct() %>% 
  pivot_longer(cols = c(`DNase-seq`, H3K27ac), names_to = "assay", values_to = "rpm")

# add enhancer activity for combined dataset
enh_activity <- enh_activity %>% 
  mutate(dataset_label = "Combined K562 training") %>% 
  bind_rows(enh_activity, .)

# plot enhancer activity distributions of all tested CRISPR E-G pairs
enh_activity_plot <- ggplot(enh_activity,
                            aes(y = dataset_label, x = rpm + 1, color = assay, fill = assay)) +
  facet_wrap(~ assay) +
  geom_violin() +
  geom_boxplot(width = 0.1, outlier.shape = NA, color = "black", fill = "NA") +
  labs(x = "Reads per million (RPM)", title = "Enhancer activity") +
  scale_fill_manual(values = c("DNase-seq" = "steelblue", "H3K27ac" = "orange")) +
  scale_color_manual(values = c("DNase-seq" = "steelblue", "H3K27ac" = "orange")) +
  scale_x_log10() +
  theme_classic() +
  theme(legend.position = "none", text = element_text(size = 12), axis.title.y = element_blank(),
        strip.background = element_blank(), strip.text.x = element_text(size = 12),
        plot.title = element_text(size = 14))
```

```{r}
# select distance to TSS for each E-G pair
dist_to_tss <- select(combinedData, name, dataset_label, distanceToTSS)

# add distance to TSS for combined dataset
dist_to_tss <- dist_to_tss %>% 
  mutate(dataset_label = "Combined K562 training") %>% 
  bind_rows(dist_to_tss, .)

# plot distance to TSS distribution
distance_plot <- ggplot(dist_to_tss, aes(x = dataset_label, y = distanceToTSS / 1e6)) +
  facet_wrap(~"Distance to TSS") +
  geom_violin(color = "gray55", fill = "gray55") +
  geom_boxplot(width = 0.1, outlier.shape = NA, color = "black", fill = "NA") +
  labs(y = "Distance to TSS (Mb)", title = "Distance") +
  scale_y_continuous(limits = c(0, 2.5)) +
  coord_flip() +
  theme_classic() +
  theme(legend.position = "none", text = element_text(size = 12), axis.title.y = element_blank(),
        axis.text.y = element_blank(), axis.ticks.y = element_blank(),
        strip.background = element_blank(), strip.text.x = element_text(size = 12),
        plot.title = element_text(size = 14))
```

```{r, fig.height=4.5, fig.width=7}
# arrange property plots for form panel C
eg_properties <- plot_grid(enh_activity_plot, distance_plot, rel_widths = c(2, 0.75))
```

***

## Detected effect sizes

```{r}
# function to plot the CRISPR effect sizes vs. distance to TSS
plot_effect_sizes <- function(data, title) {
  
  # plot effect sizes as a function of distanve
  crispr_effects <- ggplot(data,
                           aes(x = distanceToTSS / 1e6, y = EffectSize, color = crispr_outcome)) +
    geom_point() +
    geom_point(data = filter(data, crispr_outcome == "Pos.")) +
    geom_hline(yintercept = 0, color = "black") +
    labs(x = "Distance to TSS (Mb)", y = "CRISPRi effect size\n(% expression change)",
         color = "CRISPR", title = title) +
    scale_y_continuous(labels = scales::percent, limits = c(-1, 0.5)) +
    scale_color_manual(values = c("Pos." = "firebrick2", "Neg." = "gray55")) +
    theme_classic() +
    theme(legend.position = "bottom")

# add marginal density
ggMarginal(crispr_effects, type = "density", groupColour = TRUE)
  
}
```

```{r}
# add descriptive column of CRISPR outcome (positive or negative) and order datasets for plots
combinedData <- combinedData %>% 
  mutate(crispr_outcome = if_else(Regulated == TRUE, true = "Pos.", false = "Neg.")) %>% 
  mutate(dataset_label = fct_rev(dataset_label))

# split combined CRISPR data by dataset
combinedData_per_datasets <- split(combinedData, f = combinedData$dataset_label)

# create effect size versus distance to TSS plots for each dataset
es_plots <- mapply(FUN = plot_effect_sizes, data = combinedData_per_datasets,
                   title = names(combinedData_per_datasets), SIMPLIFY = FALSE)

# arrange plots into panel
crispr_effect_sizes <- plot_grid(plotlist = es_plots, nrow = 1)
```

***

## Assemble figure
```{r, fig.height=10, fig.width=12}
# arrange all panels into one figure
plot_grid(
  plot_grid(power_gasp_plot, power_schrai_plot, nrow = 1, scale = 0.9, labels = c("b", "c")),
  plot_grid(n_crispr_pairs, eg_properties, nrow = 1, scale = 0.9, labels = c("d", "e")),
  plot_grid(crispr_effect_sizes, scale = 0.9, labels = "f"),
  ncol = 1,
  rel_heights = c(0.75, 0.8, 1)
  )

# save to .pdf file
ggsave(file = "results/manuscript/plots/figS1.1_crispr_training_data.pdf", height = 10, width = 12)
```

***

## Session information
This document was produced using following packages:
```{r sessionInfo}
sessionInfo()
```
